Repository shivani1706/photoholic, pull requests merged in 2022-10, with the labels that each got.

#3 updated index.css
  index.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#13 Added Screenshots in README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#18 updated index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#20 footer changed
  index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#25 updated readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#26 updated screenshot in readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#27 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#30 Added "Save" button functionality for each image and fixed the off-centered social media overlay
  index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#36 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
